<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Fitting arima models | Introduction to econometrics</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Fitting arima models | Introduction to econometrics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Fitting arima models | Introduction to econometrics" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Boyko Amarov" />


<meta name="date" content="2021-01-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="covariance.html"/>
<link rel="next" href="unit-root-tests.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>

<script>
/* ========================================================================
 * Bootstrap: transition.js v3.3.7
 * http://getbootstrap.com/javascript/#transitions
 * ========================================================================
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 * ======================================================================== */


+function ($) {
  'use strict';

  // CSS TRANSITION SUPPORT (Shoutout: http://www.modernizr.com/)
  // ============================================================

  function transitionEnd() {
    var el = document.createElement('bootstrap')

    var transEndEventNames = {
      WebkitTransition : 'webkitTransitionEnd',
      MozTransition    : 'transitionend',
      OTransition      : 'oTransitionEnd otransitionend',
      transition       : 'transitionend'
    }

    for (var name in transEndEventNames) {
      if (el.style[name] !== undefined) {
        return { end: transEndEventNames[name] }
      }
    }

    return false // explicit for ie8 (  ._.)
  }

  // http://blog.alexmaccaw.com/css-transitions
  $.fn.emulateTransitionEnd = function (duration) {
    var called = false
    var $el = this
    $(this).one('bsTransitionEnd', function () { called = true })
    var callback = function () { if (!called) $($el).trigger($.support.transition.end) }
    setTimeout(callback, duration)
    return this
  }

  $(function () {
    $.support.transition = transitionEnd()

    if (!$.support.transition) return

    $.event.special.bsTransitionEnd = {
      bindType: $.support.transition.end,
      delegateType: $.support.transition.end,
      handle: function (e) {
        if ($(e.target).is(this)) return e.handleObj.handler.apply(this, arguments)
      }
    }
  })

}(jQuery);

</script>
<script>
/* ========================================================================
 * Bootstrap: collapse.js v3.3.7
 * http://getbootstrap.com/javascript/#collapse
 * ========================================================================
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 * ======================================================================== */

/* jshint latedef: false */

+function ($) {
  'use strict';

  // COLLAPSE PUBLIC CLASS DEFINITION
  // ================================

  var Collapse = function (element, options) {
    this.$element      = $(element)
    this.options       = $.extend({}, Collapse.DEFAULTS, options)
    this.$trigger      = $('[data-toggle="collapse"][href="#' + element.id + '"],' +
                           '[data-toggle="collapse"][data-target="#' + element.id + '"]')
    this.transitioning = null

    if (this.options.parent) {
      this.$parent = this.getParent()
    } else {
      this.addAriaAndCollapsedClass(this.$element, this.$trigger)
    }

    if (this.options.toggle) this.toggle()
  }

  Collapse.VERSION  = '3.3.7'

  Collapse.TRANSITION_DURATION = 350

  Collapse.DEFAULTS = {
    toggle: true
  }

  Collapse.prototype.dimension = function () {
    var hasWidth = this.$element.hasClass('width')
    return hasWidth ? 'width' : 'height'
  }

  Collapse.prototype.show = function () {
    if (this.transitioning || this.$element.hasClass('in')) return

    var activesData
    var actives = this.$parent && this.$parent.children('.panel').children('.in, .collapsing')

    if (actives && actives.length) {
      activesData = actives.data('bs.collapse')
      if (activesData && activesData.transitioning) return
    }

    var startEvent = $.Event('show.bs.collapse')
    this.$element.trigger(startEvent)
    if (startEvent.isDefaultPrevented()) return

    if (actives && actives.length) {
      Plugin.call(actives, 'hide')
      activesData || actives.data('bs.collapse', null)
    }

    var dimension = this.dimension()

    this.$element
      .removeClass('collapse')
      .addClass('collapsing')[dimension](0)
      .attr('aria-expanded', true)

    this.$trigger
      .removeClass('collapsed')
      .attr('aria-expanded', true)

    this.transitioning = 1

    var complete = function () {
      this.$element
        .removeClass('collapsing')
        .addClass('collapse in')[dimension]('')
      this.transitioning = 0
      this.$element
        .trigger('shown.bs.collapse')
    }

    if (!$.support.transition) return complete.call(this)

    var scrollSize = $.camelCase(['scroll', dimension].join('-'))

    this.$element
      .one('bsTransitionEnd', $.proxy(complete, this))
      .emulateTransitionEnd(Collapse.TRANSITION_DURATION)[dimension](this.$element[0][scrollSize])
  }

  Collapse.prototype.hide = function () {
    if (this.transitioning || !this.$element.hasClass('in')) return

    var startEvent = $.Event('hide.bs.collapse')
    this.$element.trigger(startEvent)
    if (startEvent.isDefaultPrevented()) return

    var dimension = this.dimension()

    this.$element[dimension](this.$element[dimension]())[0].offsetHeight

    this.$element
      .addClass('collapsing')
      .removeClass('collapse in')
      .attr('aria-expanded', false)

    this.$trigger
      .addClass('collapsed')
      .attr('aria-expanded', false)

    this.transitioning = 1

    var complete = function () {
      this.transitioning = 0
      this.$element
        .removeClass('collapsing')
        .addClass('collapse')
        .trigger('hidden.bs.collapse')
    }

    if (!$.support.transition) return complete.call(this)

    this.$element
      [dimension](0)
      .one('bsTransitionEnd', $.proxy(complete, this))
      .emulateTransitionEnd(Collapse.TRANSITION_DURATION)
  }

  Collapse.prototype.toggle = function () {
    this[this.$element.hasClass('in') ? 'hide' : 'show']()
  }

  Collapse.prototype.getParent = function () {
    return $(this.options.parent)
      .find('[data-toggle="collapse"][data-parent="' + this.options.parent + '"]')
      .each($.proxy(function (i, element) {
        var $element = $(element)
        this.addAriaAndCollapsedClass(getTargetFromTrigger($element), $element)
      }, this))
      .end()
  }

  Collapse.prototype.addAriaAndCollapsedClass = function ($element, $trigger) {
    var isOpen = $element.hasClass('in')

    $element.attr('aria-expanded', isOpen)
    $trigger
      .toggleClass('collapsed', !isOpen)
      .attr('aria-expanded', isOpen)
  }

  function getTargetFromTrigger($trigger) {
    var href
    var target = $trigger.attr('data-target')
      || (href = $trigger.attr('href')) && href.replace(/.*(?=#[^\s]+$)/, '') // strip for ie7

    return $(target)
  }


  // COLLAPSE PLUGIN DEFINITION
  // ==========================

  function Plugin(option) {
    return this.each(function () {
      var $this   = $(this)
      var data    = $this.data('bs.collapse')
      var options = $.extend({}, Collapse.DEFAULTS, $this.data(), typeof option == 'object' && option)

      if (!data && options.toggle && /show|hide/.test(option)) options.toggle = false
      if (!data) $this.data('bs.collapse', (data = new Collapse(this, options)))
      if (typeof option == 'string') data[option]()
    })
  }

  var old = $.fn.collapse

  $.fn.collapse             = Plugin
  $.fn.collapse.Constructor = Collapse


  // COLLAPSE NO CONFLICT
  // ====================

  $.fn.collapse.noConflict = function () {
    $.fn.collapse = old
    return this
  }


  // COLLAPSE DATA-API
  // =================

  $(document).on('click.bs.collapse.data-api', '[data-toggle="collapse"]', function (e) {
    var $this   = $(this)

    if (!$this.attr('data-target')) e.preventDefault()

    var $target = getTargetFromTrigger($this)
    var data    = $target.data('bs.collapse')
    var option  = data ? 'toggle' : $this.data()

    Plugin.call($target, option)
  })

}(jQuery);
</script>
<script>
window.initializeCodeFolding = function(show) {

  // handlers for show-all and hide all
  $("#rmd-show-all-code").click(function() {
    $('div.r-code-collapse').each(function() {
      $(this).collapse('show');
    });
  });
  $("#rmd-hide-all-code").click(function() {
    $('div.r-code-collapse').each(function() {
      $(this).collapse('hide');
    });
  });

  // index for unique code element ids
  var currentIndex = 1;

  // select all R code blocks
  var rCodeBlocks = $('pre.sourceCode, pre.r, pre.python, pre.bash, pre.sql, pre.cpp, pre.stan, pre.js');
  rCodeBlocks.each(function() {

    // create a collapsable div to wrap the code in
    var div = $('<div class="collapse r-code-collapse"></div>');
    if (show)
      div.addClass('in');
    var id = 'rcode-643E0F36' + currentIndex++;
    div.attr('id', id);
    $(this).before(div);
    $(this).detach().appendTo(div);

    // add a show code button right above
    var showCodeText = $('<span>' + (show ? 'Hide' : 'Code') + '</span>');
    var showCodeButton = $('<button type="button" class="btn btn-default btn-xs code-folding-btn pull-right"></button>');
    showCodeButton.append(showCodeText);
    showCodeButton
        .attr('data-toggle', 'collapse')
        .attr('data-target', '#' + id)
        .attr('aria-expanded', show)
        .attr('aria-controls', id);

    var buttonRow = $('<div class="row"></div>');
    var buttonCol = $('<div class="col-md-12"></div>');

    buttonCol.append(showCodeButton);
    buttonRow.append(buttonCol);

    div.before(buttonRow);

    // update state of button on show/hide
    div.on('hidden.bs.collapse', function () {
      showCodeText.text('Code');
    });
    div.on('show.bs.collapse', function () {
      showCodeText.text('Hide');
    });
  });

}
</script>
<script>
/* ========================================================================
 * Bootstrap: dropdown.js v3.3.7
 * http://getbootstrap.com/javascript/#dropdowns
 * ========================================================================
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 * ======================================================================== */


+function ($) {
  'use strict';

  // DROPDOWN CLASS DEFINITION
  // =========================

  var backdrop = '.dropdown-backdrop'
  var toggle   = '[data-toggle="dropdown"]'
  var Dropdown = function (element) {
    $(element).on('click.bs.dropdown', this.toggle)
  }

  Dropdown.VERSION = '3.3.7'

  function getParent($this) {
    var selector = $this.attr('data-target')

    if (!selector) {
      selector = $this.attr('href')
      selector = selector && /#[A-Za-z]/.test(selector) && selector.replace(/.*(?=#[^\s]*$)/, '') // strip for ie7
    }

    var $parent = selector && $(selector)

    return $parent && $parent.length ? $parent : $this.parent()
  }

  function clearMenus(e) {
    if (e && e.which === 3) return
    $(backdrop).remove()
    $(toggle).each(function () {
      var $this         = $(this)
      var $parent       = getParent($this)
      var relatedTarget = { relatedTarget: this }

      if (!$parent.hasClass('open')) return

      if (e && e.type == 'click' && /input|textarea/i.test(e.target.tagName) && $.contains($parent[0], e.target)) return

      $parent.trigger(e = $.Event('hide.bs.dropdown', relatedTarget))

      if (e.isDefaultPrevented()) return

      $this.attr('aria-expanded', 'false')
      $parent.removeClass('open').trigger($.Event('hidden.bs.dropdown', relatedTarget))
    })
  }

  Dropdown.prototype.toggle = function (e) {
    var $this = $(this)

    if ($this.is('.disabled, :disabled')) return

    var $parent  = getParent($this)
    var isActive = $parent.hasClass('open')

    clearMenus()

    if (!isActive) {
      if ('ontouchstart' in document.documentElement && !$parent.closest('.navbar-nav').length) {
        // if mobile we use a backdrop because click events don't delegate
        $(document.createElement('div'))
          .addClass('dropdown-backdrop')
          .insertAfter($(this))
          .on('click', clearMenus)
      }

      var relatedTarget = { relatedTarget: this }
      $parent.trigger(e = $.Event('show.bs.dropdown', relatedTarget))

      if (e.isDefaultPrevented()) return

      $this
        .trigger('focus')
        .attr('aria-expanded', 'true')

      $parent
        .toggleClass('open')
        .trigger($.Event('shown.bs.dropdown', relatedTarget))
    }

    return false
  }

  Dropdown.prototype.keydown = function (e) {
    if (!/(38|40|27|32)/.test(e.which) || /input|textarea/i.test(e.target.tagName)) return

    var $this = $(this)

    e.preventDefault()
    e.stopPropagation()

    if ($this.is('.disabled, :disabled')) return

    var $parent  = getParent($this)
    var isActive = $parent.hasClass('open')

    if (!isActive && e.which != 27 || isActive && e.which == 27) {
      if (e.which == 27) $parent.find(toggle).trigger('focus')
      return $this.trigger('click')
    }

    var desc = ' li:not(.disabled):visible a'
    var $items = $parent.find('.dropdown-menu' + desc)

    if (!$items.length) return

    var index = $items.index(e.target)

    if (e.which == 38 && index > 0)                 index--         // up
    if (e.which == 40 && index < $items.length - 1) index++         // down
    if (!~index)                                    index = 0

    $items.eq(index).trigger('focus')
  }


  // DROPDOWN PLUGIN DEFINITION
  // ==========================

  function Plugin(option) {
    return this.each(function () {
      var $this = $(this)
      var data  = $this.data('bs.dropdown')

      if (!data) $this.data('bs.dropdown', (data = new Dropdown(this)))
      if (typeof option == 'string') data[option].call($this)
    })
  }

  var old = $.fn.dropdown

  $.fn.dropdown             = Plugin
  $.fn.dropdown.Constructor = Dropdown


  // DROPDOWN NO CONFLICT
  // ====================

  $.fn.dropdown.noConflict = function () {
    $.fn.dropdown = old
    return this
  }


  // APPLY TO STANDARD DROPDOWN ELEMENTS
  // ===================================

  $(document)
    .on('click.bs.dropdown.data-api', clearMenus)
    .on('click.bs.dropdown.data-api', '.dropdown form', function (e) { e.stopPropagation() })
    .on('click.bs.dropdown.data-api', toggle, Dropdown.prototype.toggle)
    .on('keydown.bs.dropdown.data-api', toggle, Dropdown.prototype.keydown)
    .on('keydown.bs.dropdown.data-api', '.dropdown-menu', Dropdown.prototype.keydown)

}(jQuery);
</script>
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
.row { display: flex; }
.collapse { display: none; }
.in { display:block }
.pull-right > .dropdown-menu {
    right: 0;
    left: auto;
}
.open > .dropdown-menu {
    display: block;
}
.dropdown-menu {
    position: absolute;
    top: 100%;
    left: 0;
    z-index: 1000;
    display: none;
    float: left;
    min-width: 160px;
    padding: 5px 0;
    margin: 2px 0 0;
    font-size: 14px;
    text-align: left;
    list-style: none;
    background-color: #fff;
    -webkit-background-clip: padding-box;
    background-clip: padding-box;
    border: 1px solid #ccc;
    border: 1px solid rgba(0,0,0,.15);
    border-radius: 4px;
    -webkit-box-shadow: 0 6px 12px rgba(0,0,0,.175);
    box-shadow: 0 6px 12px rgba(0,0,0,.175);
}
</style>
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to econometrics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="covariance.html"><a href="covariance.html"><i class="fa fa-check"></i><b>2</b> Sample covariance and sample correlation</a><ul>
<li class="chapter" data-level="2.1" data-path="covariance.html"><a href="covariance.html#time-series-analysis-class-2"><i class="fa fa-check"></i><b>2.1</b> Time series analysis class 2</a></li>
<li class="chapter" data-level="2.2" data-path="covariance.html"><a href="covariance.html#purely-random-process-white-noise"><i class="fa fa-check"></i><b>2.2</b> Purely random process (white noise)</a></li>
<li class="chapter" data-level="2.3" data-path="covariance.html"><a href="covariance.html#simulating-white-noise"><i class="fa fa-check"></i><b>2.3</b> Simulating white noise</a></li>
<li class="chapter" data-level="2.4" data-path="covariance.html"><a href="covariance.html#sample-empirical-covariance"><i class="fa fa-check"></i><b>2.4</b> Sample (empirical) covariance</a><ul>
<li class="chapter" data-level="2.4.1" data-path="covariance.html"><a href="covariance.html#positive-linear-dependency"><i class="fa fa-check"></i><b>2.4.1</b> Positive linear dependency</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="covariance.html"><a href="covariance.html#exercise"><i class="fa fa-check"></i><b>2.5</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="fit.html"><a href="fit.html"><i class="fa fa-check"></i><b>3</b> Fitting arima models</a><ul>
<li class="chapter" data-level="3.1" data-path="fit.html"><a href="fit.html#data-exploration"><i class="fa fa-check"></i><b>3.1</b> Data exploration</a></li>
<li class="chapter" data-level="3.2" data-path="fit.html"><a href="fit.html#fit-an-arp-process"><i class="fa fa-check"></i><b>3.2</b> Fit an AR(p) process</a></li>
<li class="chapter" data-level="3.3" data-path="fit.html"><a href="fit.html#model-choice-1"><i class="fa fa-check"></i><b>3.3</b> Model choice (1)</a></li>
<li class="chapter" data-level="3.4" data-path="fit.html"><a href="fit.html#model-choice-2"><i class="fa fa-check"></i><b>3.4</b> Model choice (2)</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="unit-root-tests.html"><a href="unit-root-tests.html"><i class="fa fa-check"></i><b>4</b> Unit root tests</a><ul>
<li class="chapter" data-level="4.1" data-path="unit-root-tests.html"><a href="unit-root-tests.html#dickey-fuller-tests"><i class="fa fa-check"></i><b>4.1</b> Dickey-Fuller tests</a><ul>
<li class="chapter" data-level="4.1.1" data-path="unit-root-tests.html"><a href="unit-root-tests.html#no-level-no-trend"><i class="fa fa-check"></i><b>4.1.1</b> No level, no trend</a></li>
<li class="chapter" data-level="4.1.2" data-path="unit-root-tests.html"><a href="unit-root-tests.html#non-zero-level-no-trend"><i class="fa fa-check"></i><b>4.1.2</b> Non-zero level, no trend</a></li>
<li class="chapter" data-level="4.1.3" data-path="unit-root-tests.html"><a href="unit-root-tests.html#trend"><i class="fa fa-check"></i><b>4.1.3</b> Trend</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to econometrics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="fit" class="section level1">
<h1><span class="header-section-number">Chapter 3</span> Fitting arima models</h1>
<p>Let us look at a real dataset of Bulgarian quarterly GDP figures from 2000 to 2017. Our goal will
be to select a mathematical model for the quarterly GDP growth rates.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="fit.html#cb24-1"></a><span class="kw">library</span>(xts)</span>
<span id="cb24-2"><a href="fit.html#cb24-2"></a><span class="co"># a) Read data</span></span>
<span id="cb24-3"><a href="fit.html#cb24-3"></a>gdp &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&#39;https://raw.githubusercontent.com/feb-uni-sofia/timeseries-20202021/main/data/gdp_bg_qrt_2000-2017.csv&#39;</span>)</span>
<span id="cb24-4"><a href="fit.html#cb24-4"></a></span>
<span id="cb24-5"><a href="fit.html#cb24-5"></a><span class="co">## Create a time index from the column names &quot;Index&quot; in the gdp dataset.</span></span>
<span id="cb24-6"><a href="fit.html#cb24-6"></a>timeIndex &lt;-<span class="st"> </span><span class="kw">as.yearqtr</span>(gdp<span class="op">$</span>Index, <span class="dt">format =</span> <span class="st">&#39;%YQ%q&#39;</span>)</span>
<span id="cb24-7"><a href="fit.html#cb24-7"></a><span class="co">## Combine the values of the GDP (column called &quot;GDP&quot;) and the time index to create</span></span>
<span id="cb24-8"><a href="fit.html#cb24-8"></a><span class="co">## a time series object.</span></span>
<span id="cb24-9"><a href="fit.html#cb24-9"></a>gdpSeries &lt;-<span class="st"> </span><span class="kw">xts</span>(gdp<span class="op">$</span>GDP, <span class="dt">order.by =</span> timeIndex)</span></code></pre></div>
<p>Before we compute the quarterly growth rates we will first examine the original series.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="fit.html#cb25-1"></a><span class="kw">plot</span>(gdpSeries)</span></code></pre></div>
<p><img src="timeseries2020_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="fit.html#cb26-1"></a><span class="kw">acf</span>(gdpSeries)</span></code></pre></div>
<p><img src="timeseries2020_files/figure-html/unnamed-chunk-9-2.png" width="672" />
A prominent feature in the dataset is a strong seasonal effect. Furthermore, the data appears to have a positive trend at least until 2009.</p>
<p>Let us denote the data in this time series with
<span class="math display">\[
y_{1}, y_{2}, y_{3},\ldots,y_{T}\\
\]</span>
where <span class="math inline">\(t = 1\)</span> corresponds to the first quarter of 2000 and <span class="math inline">\(t = T = 71\)</span> corresponds to the third quarter of 2017 (the last observation in the dataset).</p>
<p>To compute the growth rates for each quarter compared to the same quarter during the previous year we will use a continuous growth rate defined as follows:</p>
<p><span class="math display">\[
growthRate_{t} = \frac{y_{t} - y_{t - 1}}{y_{t - 4}} \approx \log(y_{t}) - \log(y_{t - 4})
\]</span></p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="fit.html#cb27-1"></a><span class="co">## First we take the 4-th lag of the series and afterwards we take the difference</span></span>
<span id="cb27-2"><a href="fit.html#cb27-2"></a><span class="co">## between the log values of the original series and the log values of the lag(4-th lag)</span></span>
<span id="cb27-3"><a href="fit.html#cb27-3"></a>growthSeries &lt;-<span class="st"> </span><span class="kw">log</span>(gdpSeries) <span class="op">-</span><span class="st"> </span><span class="kw">log</span>(<span class="kw">lag</span>(gdpSeries, <span class="dt">k =</span> <span class="dv">4</span>))</span></code></pre></div>
<div id="data-exploration" class="section level2">
<h2><span class="header-section-number">3.1</span> Data exploration</h2>
<p>In the previous section we have defined the growth rates we are about to model and we
have computed the necessary growth rates series. Please note that the first four values
of the growth series are missing (undefined), because the first quarter of 2001 is the first
data point were we can apply the formula use to compute these growth rates. We cannot apply it to the last quarter of 2000, for example, because we lack data on the GDP in the last quarter of 1999.</p>
<p>Before we begin to build our model let us examine the plot of the series as well as
its autocorrelation and partial autocorrelation plots.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="fit.html#cb28-1"></a><span class="co">## mean(growthSeries, na.rm = TRUE)</span></span>
<span id="cb28-2"><a href="fit.html#cb28-2"></a><span class="kw">plot</span>(growthSeries)</span></code></pre></div>
<p><img src="timeseries2020_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="fit.html#cb29-1"></a><span class="co">## As the growth series contains missing values we must instruct acf and pacf to </span></span>
<span id="cb29-2"><a href="fit.html#cb29-2"></a><span class="co">## exclude these, otherwise acf/pacf will throw errors.</span></span>
<span id="cb29-3"><a href="fit.html#cb29-3"></a></span>
<span id="cb29-4"><a href="fit.html#cb29-4"></a><span class="co">## Draw the autocorrelation plot</span></span>
<span id="cb29-5"><a href="fit.html#cb29-5"></a><span class="kw">acf</span>(growthSeries, <span class="dt">na.action =</span> na.omit)</span></code></pre></div>
<p><img src="timeseries2020_files/figure-html/unnamed-chunk-11-2.png" width="672" /></p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="fit.html#cb30-1"></a><span class="co">## Draw the partial autocorrelation plot</span></span>
<span id="cb30-2"><a href="fit.html#cb30-2"></a><span class="kw">pacf</span>(growthSeries, <span class="dt">na.action =</span> na.omit)</span></code></pre></div>
<p><img src="timeseries2020_files/figure-html/unnamed-chunk-11-3.png" width="672" /></p>
<p>The ACF plot show slowly decaying autocorrelations that disappear after approx. one year. This appears consistent with autoregressive models. The partial autocorrelation plot shows a single large and significat partial autocorrelation at lag 1. This is consistent with a first order autoregressive process so we will try fitting one as our next step.</p>
</div>
<div id="fit-an-arp-process" class="section level2">
<h2><span class="header-section-number">3.2</span> Fit an AR(p) process</h2>
<p>Based on the exploratory analysis we have chosen a AR(1) model for the GDP growth data.</p>
<p><span class="math display">\[
y_{t} = \delta + \alpha y_{t - 1} + u_{t}, u_{t} \sim WN(\sigma^2): \text{AR(1)}
\]</span></p>
<p>This model has two coefficients that we need to estimate (learn) from the data: <span class="math inline">\(\delta\)</span> and <span class="math inline">\(\alpha\)</span>. We will use the <code>arima</code> function to compute these estimates using a maximum likelihood method (not discussed in this class, but similar in spirit to the least squares method from the econometrics class).</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="fit.html#cb31-1"></a><span class="co">## Similar to lm()</span></span>
<span id="cb31-2"><a href="fit.html#cb31-2"></a><span class="co">## ARIMA(p, d, q)</span></span>
<span id="cb31-3"><a href="fit.html#cb31-3"></a>fitAR1 &lt;-<span class="st"> </span><span class="kw">arima</span>(growthSeries, <span class="dt">order =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>)) <span class="co">## AR(1)</span></span>
<span id="cb31-4"><a href="fit.html#cb31-4"></a>fitAR1 <span class="co">## ar1: alpha</span></span></code></pre></div>
<pre><code>## 
## Call:
## arima(x = growthSeries, order = c(1, 0, 0))
## 
## Coefficients:
##          ar1  intercept
##       0.8152     0.0353
## s.e.  0.0665     0.0109
## 
## sigma^2 estimated as 0.0003066:  log likelihood = 175.4,  aic = -344.79</code></pre>
<p>from the output of the <code>arima</code> function we obtain the estimates for <span class="math inline">\(\delta\)</span> and <span class="math inline">\(\alpha\)</span>.</p>
<p><span class="math display">\[
\hat{y}_{t + 1} = \hat{\delta} + \hat{\alpha} y_{t}\\
\hat{\alpha} = 0.8152\\
\hat{\delta} = 0.0353\\
\hat{y_{t}} = 0.0353  + 0.8152\hat{y}_{t - 1}\\
\]</span>
To compute a one-period ahead prediction using the fitted model, use the <code>predict</code> function.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="fit.html#cb33-1"></a><span class="co">## Use predict to compute the one </span></span>
<span id="cb33-2"><a href="fit.html#cb33-2"></a><span class="kw">predict</span>(fitAR1, <span class="dt">n.ahead =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## $pred
##          Qtr4
## 18 0.03716986
## 
## $se
##          Qtr4
## 18 0.01751059</code></pre>
<p>We predict a 3.7% percent growth for the last quarter of 2017 (compared to the last quarter of 2016).
The <code>predict</code> function outputs two values: the point prediction and the estimated standard error of this prediction. To express the uncertainty inherent in the prediction we compute an approx. 95 percent prediction interval using the standard error.</p>
<p>An approximate 95% prediction interval for the growth rate in 2017Q4 is given
by [0.03716986 - 2<em>0.01751059, 0.03716986 + 2</em>0.01751059] = [0.00214868, 0.07219104].</p>
<p>Note that ARIMA models in general are best suited for short-term predictions, because the quality of the prediction depends on the strength of the autocorrelations in the series (associations between present and past values). For periods far away from the latest observed value the ARIMA predictions collapse to the sample mean of the series.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="fit.html#cb35-1"></a><span class="co">## Use predict to compute the one </span></span>
<span id="cb35-2"><a href="fit.html#cb35-2"></a><span class="kw">predict</span>(fitAR1, <span class="dt">n.ahead =</span> <span class="dv">50</span>)</span></code></pre></div>
<pre><code>## $pred
##          Qtr1       Qtr2       Qtr3       Qtr4
## 18                                  0.03716986
## 19 0.03681630 0.03652808 0.03629314 0.03610162
## 20 0.03594551 0.03581825 0.03571451 0.03562994
## 21 0.03556101 0.03550482 0.03545901 0.03542167
## 22 0.03539124 0.03536642 0.03534620 0.03532971
## 23 0.03531627 0.03530532 0.03529639 0.03528911
## 24 0.03528317 0.03527834 0.03527439 0.03527118
## 25 0.03526856 0.03526642 0.03526468 0.03526326
## 26 0.03526210 0.03526116 0.03526039 0.03525977
## 27 0.03525925 0.03525884 0.03525850 0.03525822
## 28 0.03525800 0.03525781 0.03525766 0.03525754
## 29 0.03525744 0.03525736 0.03525729 0.03525724
## 30 0.03525720 0.03525716 0.03525713 0.03525711
## 31 0.03525709                                 
## 
## $se
##          Qtr1       Qtr2       Qtr3       Qtr4
## 18                                  0.01751059
## 19 0.02259132 0.02541172 0.02712416 0.02820461
## 20 0.02890024 0.02935336 0.02965063 0.02984652
## 21 0.02997598 0.03006170 0.03011852 0.03015622
## 22 0.03018125 0.03019787 0.03020890 0.03021624
## 23 0.03022111 0.03022434 0.03022649 0.03022792
## 24 0.03022887 0.03022950 0.03022992 0.03023020
## 25 0.03023039 0.03023051 0.03023059 0.03023064
## 26 0.03023068 0.03023070 0.03023072 0.03023073
## 27 0.03023074 0.03023074 0.03023075 0.03023075
## 28 0.03023075 0.03023075 0.03023075 0.03023075
## 29 0.03023075 0.03023075 0.03023075 0.03023075
## 30 0.03023075 0.03023075 0.03023075 0.03023075
## 31 0.03023075</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="fit.html#cb37-1"></a><span class="co">## Sample mean</span></span>
<span id="cb37-2"><a href="fit.html#cb37-2"></a><span class="kw">mean</span>(growthSeries, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 0.03524203</code></pre>
</div>
<div id="model-choice-1" class="section level2">
<h2><span class="header-section-number">3.3</span> Model choice (1)</h2>
<p>Up to now we have discussed how to estimate the coefficients of a given ARIMA model using the <code>arima</code> function and how to compute predictions with <code>predict</code>, but we didn’t question whether the model can adequately describe our data or not. A model that fits the data poorly will likely result in inadequate predictions.</p>
<p>Here we will discuss a graphical analysis of the model fit using <code>tsdiag</code>. In order to see how a poorly fitting model looks we will fit a AR(0) model to the data and examine it first.</p>
<p><span class="math display">\[
y_{t} = \delta + u_{t} \quad \text{AR(0)}
\]</span></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="fit.html#cb39-1"></a>fitAR0 &lt;-<span class="st"> </span><span class="kw">arima</span>(growthSeries, <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>))</span>
<span id="cb39-2"><a href="fit.html#cb39-2"></a>fitAR0</span></code></pre></div>
<pre><code>## 
## Call:
## arima(x = growthSeries, order = c(0, 0, 0))
## 
## Coefficients:
##       intercept
##          0.0352
## s.e.     0.0038
## 
## sigma^2 estimated as 0.0009676:  log likelihood = 137.44,  aic = -270.89</code></pre>
<p>After fitting the AR(0) model we will examine its residuals, defined as:</p>
<p><span class="math display">\[
r_{t} = y_{t} - \hat{y}_t
\]</span></p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="fit.html#cb41-1"></a><span class="kw">tsdiag</span>(fitAR0)</span></code></pre></div>
<p><img src="timeseries2020_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>The <code>tsdiag</code> function produces three plots. The first one (top) show the standardised residuals of the model fit. For a good fit we expect to see standardised residuals that fluctuate around zero with a constant variance (fluctuations). This is not the case for the AR(0) fit. We that the residuals are positive (i.e. our model systematically underestimates the growth rates) before 2009 and are negative afterwards (i.e. our model systematically overestimates the growth rates). This points to a poor model choice. From the plot of the growth series data it is easy to see why this is happening. The AR(0) model has a single coefficient (<span class="math inline">\(\delta\)</span>) and it effectively predicts each value of the series with the sample mean of the series.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="fit.html#cb42-1"></a><span class="co">## Plot the growth series</span></span>
<span id="cb42-2"><a href="fit.html#cb42-2"></a><span class="co">## Here we use plot.zoo instead of plot.xts as we usually do, because it</span></span>
<span id="cb42-3"><a href="fit.html#cb42-3"></a><span class="co">## is easier to draw the horizontal line at the sample mean of the series.</span></span>
<span id="cb42-4"><a href="fit.html#cb42-4"></a><span class="kw">plot.zoo</span>(growthSeries)</span>
<span id="cb42-5"><a href="fit.html#cb42-5"></a></span>
<span id="cb42-6"><a href="fit.html#cb42-6"></a><span class="co">## Draw a horizontal line at the mean (0.03524)</span></span>
<span id="cb42-7"><a href="fit.html#cb42-7"></a><span class="kw">abline</span>(<span class="dt">h =</span> <span class="kw">mean</span>(growthSeries, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>), <span class="dt">col =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="timeseries2020_files/figure-html/unnamed-chunk-17-1.png" width="672" />
Because of the large shift after the financial crisis of 2009 the sample mean underestimates
the growth rates before 2009 and overestimates the growth rates after that.</p>
<p>The next two plots are related and they show the autocorrelations of the residuals. Good model should not have residuals with significant autocorrelations. For the AR(0) models the residuals are strongly correlated (as seen from the bars in the second plot) and the autocorrelation disappears only after the first year (4-th lag).</p>
<p>The last plot show p-values of the Ljung-Box autocorrelations tests. The first point refers to the p-value of the Ljung-Box test for the first-order autocorrelation. It test the hypothesis:</p>
<p><span class="math display">\[
H_{0}: \rho_{1} = 0\\
H_{1}: \rho_{1} \neq 0
\]</span>
The p-value of this test lies below the blue line in the plot which is drawn at 0.05. As the p-value is less than 0.05 we would reject the null hypothesis. A good model should not allow us to reject this hypothesis.</p>
<p>The second point in the last plot corresponds to Ljung-Box test of the hypothesis:</p>
<p><span class="math display">\[
H_{0}: \rho_{1} = \rho_{2} = 0\\
H_{1}: \text{ at least one of } \rho_{1}, \rho_{2} \neq 0\\
\]</span></p>
<p>Again, the p-value of this test leads us to reject the null hypothesis.</p>
<p>Let us now turn to the diagnostic of our initial choice of a model, the AR(1) model.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="fit.html#cb43-1"></a><span class="kw">tsdiag</span>(fitAR1)</span></code></pre></div>
<p><img src="timeseries2020_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>We see that the first plot looks much better than the one of the AR(0) model as we do not observe
systematic overestimation or underestimation.</p>
<p>Then next two plots also indicate an adequate fit as there are no significant autocorrelations in the residuals.</p>
</div>
<div id="model-choice-2" class="section level2">
<h2><span class="header-section-number">3.4</span> Model choice (2)</h2>
<p>Up until now we have examined the goodness of fit diagnostic of the AR(1) process and concluded that there are no significant autocorrelations in its residuals. However, we could raise the question whether we could fare better (i.e. describe the data better) with a more complex model, for example AR(2).</p>
<p>The AR(2) model has one more parameter than the AR(1) model and is better able to fit more closely to the data.</p>
<p>When selecting a model for a time series our goal is to find the most parsimonious model (less coefficients) that can still adequately describe the structure of the data (mean, variance, autocorrelations). One model summary statistic that can aid us in this choice is the Akaike Information Criterion (AIC). Its value is low when the model fits the data closely but is penalised for the number of coefficients estimated in that model. Thus when using the AIC we will select the model with the lowest AIC value.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="covariance.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="unit-root-tests.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/01-intro.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["timeseries2020.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
