<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Unit root tests | Introduction to econometrics</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Unit root tests | Introduction to econometrics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Unit root tests | Introduction to econometrics" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Boyko Amarov" />


<meta name="date" content="2021-01-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="fit.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>

<script>
/* ========================================================================
 * Bootstrap: transition.js v3.3.7
 * http://getbootstrap.com/javascript/#transitions
 * ========================================================================
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 * ======================================================================== */


+function ($) {
  'use strict';

  // CSS TRANSITION SUPPORT (Shoutout: http://www.modernizr.com/)
  // ============================================================

  function transitionEnd() {
    var el = document.createElement('bootstrap')

    var transEndEventNames = {
      WebkitTransition : 'webkitTransitionEnd',
      MozTransition    : 'transitionend',
      OTransition      : 'oTransitionEnd otransitionend',
      transition       : 'transitionend'
    }

    for (var name in transEndEventNames) {
      if (el.style[name] !== undefined) {
        return { end: transEndEventNames[name] }
      }
    }

    return false // explicit for ie8 (  ._.)
  }

  // http://blog.alexmaccaw.com/css-transitions
  $.fn.emulateTransitionEnd = function (duration) {
    var called = false
    var $el = this
    $(this).one('bsTransitionEnd', function () { called = true })
    var callback = function () { if (!called) $($el).trigger($.support.transition.end) }
    setTimeout(callback, duration)
    return this
  }

  $(function () {
    $.support.transition = transitionEnd()

    if (!$.support.transition) return

    $.event.special.bsTransitionEnd = {
      bindType: $.support.transition.end,
      delegateType: $.support.transition.end,
      handle: function (e) {
        if ($(e.target).is(this)) return e.handleObj.handler.apply(this, arguments)
      }
    }
  })

}(jQuery);

</script>
<script>
/* ========================================================================
 * Bootstrap: collapse.js v3.3.7
 * http://getbootstrap.com/javascript/#collapse
 * ========================================================================
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 * ======================================================================== */

/* jshint latedef: false */

+function ($) {
  'use strict';

  // COLLAPSE PUBLIC CLASS DEFINITION
  // ================================

  var Collapse = function (element, options) {
    this.$element      = $(element)
    this.options       = $.extend({}, Collapse.DEFAULTS, options)
    this.$trigger      = $('[data-toggle="collapse"][href="#' + element.id + '"],' +
                           '[data-toggle="collapse"][data-target="#' + element.id + '"]')
    this.transitioning = null

    if (this.options.parent) {
      this.$parent = this.getParent()
    } else {
      this.addAriaAndCollapsedClass(this.$element, this.$trigger)
    }

    if (this.options.toggle) this.toggle()
  }

  Collapse.VERSION  = '3.3.7'

  Collapse.TRANSITION_DURATION = 350

  Collapse.DEFAULTS = {
    toggle: true
  }

  Collapse.prototype.dimension = function () {
    var hasWidth = this.$element.hasClass('width')
    return hasWidth ? 'width' : 'height'
  }

  Collapse.prototype.show = function () {
    if (this.transitioning || this.$element.hasClass('in')) return

    var activesData
    var actives = this.$parent && this.$parent.children('.panel').children('.in, .collapsing')

    if (actives && actives.length) {
      activesData = actives.data('bs.collapse')
      if (activesData && activesData.transitioning) return
    }

    var startEvent = $.Event('show.bs.collapse')
    this.$element.trigger(startEvent)
    if (startEvent.isDefaultPrevented()) return

    if (actives && actives.length) {
      Plugin.call(actives, 'hide')
      activesData || actives.data('bs.collapse', null)
    }

    var dimension = this.dimension()

    this.$element
      .removeClass('collapse')
      .addClass('collapsing')[dimension](0)
      .attr('aria-expanded', true)

    this.$trigger
      .removeClass('collapsed')
      .attr('aria-expanded', true)

    this.transitioning = 1

    var complete = function () {
      this.$element
        .removeClass('collapsing')
        .addClass('collapse in')[dimension]('')
      this.transitioning = 0
      this.$element
        .trigger('shown.bs.collapse')
    }

    if (!$.support.transition) return complete.call(this)

    var scrollSize = $.camelCase(['scroll', dimension].join('-'))

    this.$element
      .one('bsTransitionEnd', $.proxy(complete, this))
      .emulateTransitionEnd(Collapse.TRANSITION_DURATION)[dimension](this.$element[0][scrollSize])
  }

  Collapse.prototype.hide = function () {
    if (this.transitioning || !this.$element.hasClass('in')) return

    var startEvent = $.Event('hide.bs.collapse')
    this.$element.trigger(startEvent)
    if (startEvent.isDefaultPrevented()) return

    var dimension = this.dimension()

    this.$element[dimension](this.$element[dimension]())[0].offsetHeight

    this.$element
      .addClass('collapsing')
      .removeClass('collapse in')
      .attr('aria-expanded', false)

    this.$trigger
      .addClass('collapsed')
      .attr('aria-expanded', false)

    this.transitioning = 1

    var complete = function () {
      this.transitioning = 0
      this.$element
        .removeClass('collapsing')
        .addClass('collapse')
        .trigger('hidden.bs.collapse')
    }

    if (!$.support.transition) return complete.call(this)

    this.$element
      [dimension](0)
      .one('bsTransitionEnd', $.proxy(complete, this))
      .emulateTransitionEnd(Collapse.TRANSITION_DURATION)
  }

  Collapse.prototype.toggle = function () {
    this[this.$element.hasClass('in') ? 'hide' : 'show']()
  }

  Collapse.prototype.getParent = function () {
    return $(this.options.parent)
      .find('[data-toggle="collapse"][data-parent="' + this.options.parent + '"]')
      .each($.proxy(function (i, element) {
        var $element = $(element)
        this.addAriaAndCollapsedClass(getTargetFromTrigger($element), $element)
      }, this))
      .end()
  }

  Collapse.prototype.addAriaAndCollapsedClass = function ($element, $trigger) {
    var isOpen = $element.hasClass('in')

    $element.attr('aria-expanded', isOpen)
    $trigger
      .toggleClass('collapsed', !isOpen)
      .attr('aria-expanded', isOpen)
  }

  function getTargetFromTrigger($trigger) {
    var href
    var target = $trigger.attr('data-target')
      || (href = $trigger.attr('href')) && href.replace(/.*(?=#[^\s]+$)/, '') // strip for ie7

    return $(target)
  }


  // COLLAPSE PLUGIN DEFINITION
  // ==========================

  function Plugin(option) {
    return this.each(function () {
      var $this   = $(this)
      var data    = $this.data('bs.collapse')
      var options = $.extend({}, Collapse.DEFAULTS, $this.data(), typeof option == 'object' && option)

      if (!data && options.toggle && /show|hide/.test(option)) options.toggle = false
      if (!data) $this.data('bs.collapse', (data = new Collapse(this, options)))
      if (typeof option == 'string') data[option]()
    })
  }

  var old = $.fn.collapse

  $.fn.collapse             = Plugin
  $.fn.collapse.Constructor = Collapse


  // COLLAPSE NO CONFLICT
  // ====================

  $.fn.collapse.noConflict = function () {
    $.fn.collapse = old
    return this
  }


  // COLLAPSE DATA-API
  // =================

  $(document).on('click.bs.collapse.data-api', '[data-toggle="collapse"]', function (e) {
    var $this   = $(this)

    if (!$this.attr('data-target')) e.preventDefault()

    var $target = getTargetFromTrigger($this)
    var data    = $target.data('bs.collapse')
    var option  = data ? 'toggle' : $this.data()

    Plugin.call($target, option)
  })

}(jQuery);
</script>
<script>
window.initializeCodeFolding = function(show) {

  // handlers for show-all and hide all
  $("#rmd-show-all-code").click(function() {
    $('div.r-code-collapse').each(function() {
      $(this).collapse('show');
    });
  });
  $("#rmd-hide-all-code").click(function() {
    $('div.r-code-collapse').each(function() {
      $(this).collapse('hide');
    });
  });

  // index for unique code element ids
  var currentIndex = 1;

  // select all R code blocks
  var rCodeBlocks = $('pre.sourceCode, pre.r, pre.python, pre.bash, pre.sql, pre.cpp, pre.stan, pre.js');
  rCodeBlocks.each(function() {

    // create a collapsable div to wrap the code in
    var div = $('<div class="collapse r-code-collapse"></div>');
    if (show)
      div.addClass('in');
    var id = 'rcode-643E0F36' + currentIndex++;
    div.attr('id', id);
    $(this).before(div);
    $(this).detach().appendTo(div);

    // add a show code button right above
    var showCodeText = $('<span>' + (show ? 'Hide' : 'Code') + '</span>');
    var showCodeButton = $('<button type="button" class="btn btn-default btn-xs code-folding-btn pull-right"></button>');
    showCodeButton.append(showCodeText);
    showCodeButton
        .attr('data-toggle', 'collapse')
        .attr('data-target', '#' + id)
        .attr('aria-expanded', show)
        .attr('aria-controls', id);

    var buttonRow = $('<div class="row"></div>');
    var buttonCol = $('<div class="col-md-12"></div>');

    buttonCol.append(showCodeButton);
    buttonRow.append(buttonCol);

    div.before(buttonRow);

    // update state of button on show/hide
    div.on('hidden.bs.collapse', function () {
      showCodeText.text('Code');
    });
    div.on('show.bs.collapse', function () {
      showCodeText.text('Hide');
    });
  });

}
</script>
<script>
/* ========================================================================
 * Bootstrap: dropdown.js v3.3.7
 * http://getbootstrap.com/javascript/#dropdowns
 * ========================================================================
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 * ======================================================================== */


+function ($) {
  'use strict';

  // DROPDOWN CLASS DEFINITION
  // =========================

  var backdrop = '.dropdown-backdrop'
  var toggle   = '[data-toggle="dropdown"]'
  var Dropdown = function (element) {
    $(element).on('click.bs.dropdown', this.toggle)
  }

  Dropdown.VERSION = '3.3.7'

  function getParent($this) {
    var selector = $this.attr('data-target')

    if (!selector) {
      selector = $this.attr('href')
      selector = selector && /#[A-Za-z]/.test(selector) && selector.replace(/.*(?=#[^\s]*$)/, '') // strip for ie7
    }

    var $parent = selector && $(selector)

    return $parent && $parent.length ? $parent : $this.parent()
  }

  function clearMenus(e) {
    if (e && e.which === 3) return
    $(backdrop).remove()
    $(toggle).each(function () {
      var $this         = $(this)
      var $parent       = getParent($this)
      var relatedTarget = { relatedTarget: this }

      if (!$parent.hasClass('open')) return

      if (e && e.type == 'click' && /input|textarea/i.test(e.target.tagName) && $.contains($parent[0], e.target)) return

      $parent.trigger(e = $.Event('hide.bs.dropdown', relatedTarget))

      if (e.isDefaultPrevented()) return

      $this.attr('aria-expanded', 'false')
      $parent.removeClass('open').trigger($.Event('hidden.bs.dropdown', relatedTarget))
    })
  }

  Dropdown.prototype.toggle = function (e) {
    var $this = $(this)

    if ($this.is('.disabled, :disabled')) return

    var $parent  = getParent($this)
    var isActive = $parent.hasClass('open')

    clearMenus()

    if (!isActive) {
      if ('ontouchstart' in document.documentElement && !$parent.closest('.navbar-nav').length) {
        // if mobile we use a backdrop because click events don't delegate
        $(document.createElement('div'))
          .addClass('dropdown-backdrop')
          .insertAfter($(this))
          .on('click', clearMenus)
      }

      var relatedTarget = { relatedTarget: this }
      $parent.trigger(e = $.Event('show.bs.dropdown', relatedTarget))

      if (e.isDefaultPrevented()) return

      $this
        .trigger('focus')
        .attr('aria-expanded', 'true')

      $parent
        .toggleClass('open')
        .trigger($.Event('shown.bs.dropdown', relatedTarget))
    }

    return false
  }

  Dropdown.prototype.keydown = function (e) {
    if (!/(38|40|27|32)/.test(e.which) || /input|textarea/i.test(e.target.tagName)) return

    var $this = $(this)

    e.preventDefault()
    e.stopPropagation()

    if ($this.is('.disabled, :disabled')) return

    var $parent  = getParent($this)
    var isActive = $parent.hasClass('open')

    if (!isActive && e.which != 27 || isActive && e.which == 27) {
      if (e.which == 27) $parent.find(toggle).trigger('focus')
      return $this.trigger('click')
    }

    var desc = ' li:not(.disabled):visible a'
    var $items = $parent.find('.dropdown-menu' + desc)

    if (!$items.length) return

    var index = $items.index(e.target)

    if (e.which == 38 && index > 0)                 index--         // up
    if (e.which == 40 && index < $items.length - 1) index++         // down
    if (!~index)                                    index = 0

    $items.eq(index).trigger('focus')
  }


  // DROPDOWN PLUGIN DEFINITION
  // ==========================

  function Plugin(option) {
    return this.each(function () {
      var $this = $(this)
      var data  = $this.data('bs.dropdown')

      if (!data) $this.data('bs.dropdown', (data = new Dropdown(this)))
      if (typeof option == 'string') data[option].call($this)
    })
  }

  var old = $.fn.dropdown

  $.fn.dropdown             = Plugin
  $.fn.dropdown.Constructor = Dropdown


  // DROPDOWN NO CONFLICT
  // ====================

  $.fn.dropdown.noConflict = function () {
    $.fn.dropdown = old
    return this
  }


  // APPLY TO STANDARD DROPDOWN ELEMENTS
  // ===================================

  $(document)
    .on('click.bs.dropdown.data-api', clearMenus)
    .on('click.bs.dropdown.data-api', '.dropdown form', function (e) { e.stopPropagation() })
    .on('click.bs.dropdown.data-api', toggle, Dropdown.prototype.toggle)
    .on('keydown.bs.dropdown.data-api', toggle, Dropdown.prototype.keydown)
    .on('keydown.bs.dropdown.data-api', '.dropdown-menu', Dropdown.prototype.keydown)

}(jQuery);
</script>
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
.row { display: flex; }
.collapse { display: none; }
.in { display:block }
.pull-right > .dropdown-menu {
    right: 0;
    left: auto;
}
.open > .dropdown-menu {
    display: block;
}
.dropdown-menu {
    position: absolute;
    top: 100%;
    left: 0;
    z-index: 1000;
    display: none;
    float: left;
    min-width: 160px;
    padding: 5px 0;
    margin: 2px 0 0;
    font-size: 14px;
    text-align: left;
    list-style: none;
    background-color: #fff;
    -webkit-background-clip: padding-box;
    background-clip: padding-box;
    border: 1px solid #ccc;
    border: 1px solid rgba(0,0,0,.15);
    border-radius: 4px;
    -webkit-box-shadow: 0 6px 12px rgba(0,0,0,.175);
    box-shadow: 0 6px 12px rgba(0,0,0,.175);
}
</style>
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introduction to econometrics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="covariance.html"><a href="covariance.html"><i class="fa fa-check"></i><b>2</b> Sample covariance and sample correlation</a><ul>
<li class="chapter" data-level="2.1" data-path="covariance.html"><a href="covariance.html#time-series-analysis-class-2"><i class="fa fa-check"></i><b>2.1</b> Time series analysis class 2</a></li>
<li class="chapter" data-level="2.2" data-path="covariance.html"><a href="covariance.html#purely-random-process-white-noise"><i class="fa fa-check"></i><b>2.2</b> Purely random process (white noise)</a></li>
<li class="chapter" data-level="2.3" data-path="covariance.html"><a href="covariance.html#simulating-white-noise"><i class="fa fa-check"></i><b>2.3</b> Simulating white noise</a></li>
<li class="chapter" data-level="2.4" data-path="covariance.html"><a href="covariance.html#sample-empirical-covariance"><i class="fa fa-check"></i><b>2.4</b> Sample (empirical) covariance</a><ul>
<li class="chapter" data-level="2.4.1" data-path="covariance.html"><a href="covariance.html#positive-linear-dependency"><i class="fa fa-check"></i><b>2.4.1</b> Positive linear dependency</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="covariance.html"><a href="covariance.html#exercise"><i class="fa fa-check"></i><b>2.5</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="fit.html"><a href="fit.html"><i class="fa fa-check"></i><b>3</b> Fitting arima models</a><ul>
<li class="chapter" data-level="3.1" data-path="fit.html"><a href="fit.html#data-exploration"><i class="fa fa-check"></i><b>3.1</b> Data exploration</a></li>
<li class="chapter" data-level="3.2" data-path="fit.html"><a href="fit.html#fit-an-arp-process"><i class="fa fa-check"></i><b>3.2</b> Fit an AR(p) process</a></li>
<li class="chapter" data-level="3.3" data-path="fit.html"><a href="fit.html#model-choice-1"><i class="fa fa-check"></i><b>3.3</b> Model choice (1)</a></li>
<li class="chapter" data-level="3.4" data-path="fit.html"><a href="fit.html#model-choice-2"><i class="fa fa-check"></i><b>3.4</b> Model choice (2)</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="unit-root-tests.html"><a href="unit-root-tests.html"><i class="fa fa-check"></i><b>4</b> Unit root tests</a><ul>
<li class="chapter" data-level="4.1" data-path="unit-root-tests.html"><a href="unit-root-tests.html#dickey-fuller-tests"><i class="fa fa-check"></i><b>4.1</b> Dickey-Fuller tests</a><ul>
<li class="chapter" data-level="4.1.1" data-path="unit-root-tests.html"><a href="unit-root-tests.html#no-level-no-trend"><i class="fa fa-check"></i><b>4.1.1</b> No level, no trend</a></li>
<li class="chapter" data-level="4.1.2" data-path="unit-root-tests.html"><a href="unit-root-tests.html#non-zero-level-no-trend"><i class="fa fa-check"></i><b>4.1.2</b> Non-zero level, no trend</a></li>
<li class="chapter" data-level="4.1.3" data-path="unit-root-tests.html"><a href="unit-root-tests.html#trend"><i class="fa fa-check"></i><b>4.1.3</b> Trend</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to econometrics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="unit-root-tests" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> Unit root tests</h1>
<div id="dickey-fuller-tests" class="section level2">
<h2><span class="header-section-number">4.1</span> Dickey-Fuller tests</h2>
<div id="no-level-no-trend" class="section level3">
<h3><span class="header-section-number">4.1.1</span> No level, no trend</h3>
<p>Consider a simple first order autoregressive model (AR(1)) with the constant <span class="math inline">\(\delta = 0\)</span>.</p>
<p><span class="math display">\[
y_{t} = \alpha_1 y_{t - 1} + u_{t}
\]</span>
We already know that for <span class="math inline">\(|alpha_1| &lt; 1\)</span> the process is stationary (i.e. its statistical properties: mean, variance and auto-covariances do not depend on the time index <span class="math inline">\(t\)</span>.). For <span class="math inline">\(\alpha_1 = 1\)</span> the process is non-stationary and behaves quite differently (see the simulation below)</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="unit-root-tests.html#cb44-1"></a><span class="kw">library</span>(xts)</span>
<span id="cb44-2"><a href="unit-root-tests.html#cb44-2"></a>n &lt;-<span class="st"> </span><span class="dv">1000</span></span>
<span id="cb44-3"><a href="unit-root-tests.html#cb44-3"></a><span class="co">## Select 1000 observations at random from the standard normal distribution</span></span>
<span id="cb44-4"><a href="unit-root-tests.html#cb44-4"></a><span class="co">## (the default for rnorm)</span></span>
<span id="cb44-5"><a href="unit-root-tests.html#cb44-5"></a>u &lt;-<span class="st"> </span><span class="kw">rnorm</span>(n)</span>
<span id="cb44-6"><a href="unit-root-tests.html#cb44-6"></a></span>
<span id="cb44-7"><a href="unit-root-tests.html#cb44-7"></a><span class="co">## Sum the selected values cumulatively, i.e. randomWalk[1] = u[1], randomWalk[2] = u[1] + u[2], etc.</span></span>
<span id="cb44-8"><a href="unit-root-tests.html#cb44-8"></a>randomWalk &lt;-<span class="st"> </span><span class="kw">cumsum</span>(u)</span>
<span id="cb44-9"><a href="unit-root-tests.html#cb44-9"></a></span>
<span id="cb44-10"><a href="unit-root-tests.html#cb44-10"></a><span class="co">## Simulate a stationary AR(1) process with alpha1 = 0.7</span></span>
<span id="cb44-11"><a href="unit-root-tests.html#cb44-11"></a>alpha1 &lt;-<span class="st"> </span><span class="fl">0.7</span></span>
<span id="cb44-12"><a href="unit-root-tests.html#cb44-12"></a>stationaryAR1 &lt;-<span class="st"> </span><span class="kw">arima.sim</span>(<span class="dt">n =</span> n, <span class="dt">model =</span> <span class="kw">list</span>(<span class="dt">ar =</span> <span class="kw">c</span>(alpha1)))</span>
<span id="cb44-13"><a href="unit-root-tests.html#cb44-13"></a>timeIndex &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="kw">as.Date</span>(<span class="st">&quot;2020-10-10&quot;</span>), <span class="dt">by =</span><span class="st">&quot;day&quot;</span>, <span class="dt">length.out =</span> n)</span>
<span id="cb44-14"><a href="unit-root-tests.html#cb44-14"></a><span class="co">## Combine the random walk and the AR(1) series into a data frame</span></span>
<span id="cb44-15"><a href="unit-root-tests.html#cb44-15"></a><span class="co">## and pass that data frame to xts. We do this, because it is easier to </span></span>
<span id="cb44-16"><a href="unit-root-tests.html#cb44-16"></a><span class="co">## plot the two series in _one_ plot when calling plot</span></span>
<span id="cb44-17"><a href="unit-root-tests.html#cb44-17"></a>series &lt;-<span class="st"> </span><span class="kw">xts</span>(<span class="kw">data.frame</span>(randomWalk, stationaryAR1), <span class="dt">order.by =</span> timeIndex)</span>
<span id="cb44-18"><a href="unit-root-tests.html#cb44-18"></a><span class="kw">plot</span>(series, <span class="dt">main =</span> <span class="kw">paste</span>(<span class="st">&quot;Random walk and AR(1) with alpha1 = &quot;</span>, alpha1))</span></code></pre></div>
<p><img src="timeseries2020_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>From the plot you should notice that the stationary series fluctuates around its expected value (0) whereas the random walk series behaves quite differently without an obvious tendency to revert to its mean.</p>
<p>For simplicity let us assume that we have observed a time series from a AR(1) model with an unknown coefficients <span class="math inline">\(\alpha_1\)</span>.</p>
<p>We would like to test the hypothesis that the coefficient <span class="math inline">\(\alpha_1 = 1\)</span> (i.e. the process is a random walk) against the one-sided alternative that it is less than 1. Looking at the model equation we could think about using a simple t-test as we did in the introductory econometrics course. It is convenient to first transform the model by subtracting <span class="math inline">\(y_{t - 1}\)</span> from both sides of the equation, because the default t-tests produced from R functions
used to fit the model to the data test the null hypothesis that the coefficient is zero.</p>
<p><span class="math display">\[
y_{t} - y_{t - 1} = \alpha_1 y_{t - 1} - y_{t - 1} + u_{t} \implies \\
y_{t} - y_{t - 1} = (\alpha_1 - 1)y_{t - 1} + u_{t}\\
\Delta y_{t} = (\alpha_1 - 1)y_{t - 1} + u_{t}
\]</span></p>
<p>With the transformed model we can now restate the unit root null hypothesis.</p>
<p><span class="math display">\[
H_{0}: \alpha_1 = 1 \Leftrightarrow H_{0}: \alpha_1 - 1 = 0
\]</span>
Instead of fitting the equation with the <code>lm</code> that we used in the econometrics course we will use a special function (<code>ur.df</code>) that is available from the <code>urca</code> package. We do this because the usual statistical theory behind the t-test for the regression coefficients does not hold under the null hypothesis and we need a special set of critical values (Dickey-Fuller critical values).</p>
<p>It is easiest to see how the test works with an example. First we generate 1000 observations from a stationary AR(1) process with <span class="math inline">\(\alpha = 0.7\)</span>. Then we plot the series and perform the t-test using the Dickey-Fuller critical values produced by <code>ur.df</code>.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="unit-root-tests.html#cb45-1"></a><span class="kw">library</span>(urca)</span>
<span id="cb45-2"><a href="unit-root-tests.html#cb45-2"></a><span class="kw">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb45-3"><a href="unit-root-tests.html#cb45-3"></a><span class="co">## Set the simulation size (number of observations)</span></span>
<span id="cb45-4"><a href="unit-root-tests.html#cb45-4"></a>n &lt;-<span class="st"> </span><span class="dv">1000</span></span>
<span id="cb45-5"><a href="unit-root-tests.html#cb45-5"></a></span>
<span id="cb45-6"><a href="unit-root-tests.html#cb45-6"></a><span class="co">##</span></span>
<span id="cb45-7"><a href="unit-root-tests.html#cb45-7"></a>alpha1 &lt;-<span class="st"> </span><span class="fl">0.7</span></span>
<span id="cb45-8"><a href="unit-root-tests.html#cb45-8"></a>stationaryAR1 &lt;-<span class="st"> </span><span class="kw">arima.sim</span>(<span class="dt">n =</span> n, <span class="dt">model =</span> <span class="kw">list</span>(<span class="dt">ar =</span> <span class="kw">c</span>(alpha1)))</span>
<span id="cb45-9"><a href="unit-root-tests.html#cb45-9"></a><span class="kw">plot</span>(stationaryAR1, <span class="dt">main =</span> <span class="kw">paste</span>(<span class="st">&quot;Stationary AR(1) process with apha1 = &quot;</span>, alpha1))</span></code></pre></div>
<p><img src="timeseries2020_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="unit-root-tests.html#cb46-1"></a><span class="kw">summary</span>(<span class="kw">ur.df</span>(stationaryAR1, <span class="dt">selectlags =</span> <span class="st">&quot;Fixed&quot;</span>, <span class="dt">lags =</span> <span class="dv">0</span>, <span class="dt">type =</span> <span class="st">&quot;none&quot;</span>))</span></code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression none 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 - 1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.8481 -0.6362  0.0061  0.6700  3.2041 
## 
## Coefficients:
##         Estimate Std. Error t value Pr(&gt;|t|)    
## z.lag.1 -0.32618    0.02339  -13.94   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1 on 998 degrees of freedom
## Multiple R-squared:  0.1631, Adjusted R-squared:  0.1622 
## F-statistic: 194.4 on 1 and 998 DF,  p-value: &lt; 2.2e-16
## 
## 
## Value of test-statistic is: -13.9437 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau1 -2.58 -1.95 -1.62</code></pre>
<p>You can find the critical values of the test in the <code>tau1</code> row in the critical values section of the <code>ur.df</code> output.
To perform the test, compare the value of the t-statistic (t-value in the <code>z.lag.1</code> row) with the set of critical values. We reject the null hypothesis that the process has a unit root for <em>small</em> values of the t-statistic. In this example the t-statistic equals -13.94 and is less than the critical value at 1pct (-2.58), so we reject the null hypothesis. For this series this is the expected result, because we know that there is no unit-root in our generated data (<span class="math inline">\(\alpha_1 = 0.7\)</span>).</p>
<p>Next, let us look at data generated from a random-walk process and let us apply the Dickey-Fuller test.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="unit-root-tests.html#cb48-1"></a><span class="kw">library</span>(xts)</span>
<span id="cb48-2"><a href="unit-root-tests.html#cb48-2"></a>n &lt;-<span class="st"> </span><span class="dv">1000</span></span>
<span id="cb48-3"><a href="unit-root-tests.html#cb48-3"></a><span class="co">## Select 1000 observations at random from the standard normal distribution</span></span>
<span id="cb48-4"><a href="unit-root-tests.html#cb48-4"></a><span class="co">## (the default for rnorm)</span></span>
<span id="cb48-5"><a href="unit-root-tests.html#cb48-5"></a>u &lt;-<span class="st"> </span><span class="kw">rnorm</span>(n)</span>
<span id="cb48-6"><a href="unit-root-tests.html#cb48-6"></a></span>
<span id="cb48-7"><a href="unit-root-tests.html#cb48-7"></a><span class="co">## Sum the selected values cumulatively, i.e. randomWalk[1] = u[1], randomWalk[2] = u[1] + u[2], etc.</span></span>
<span id="cb48-8"><a href="unit-root-tests.html#cb48-8"></a>randomWalk &lt;-<span class="st"> </span><span class="kw">cumsum</span>(u)</span>
<span id="cb48-9"><a href="unit-root-tests.html#cb48-9"></a></span>
<span id="cb48-10"><a href="unit-root-tests.html#cb48-10"></a>timeIndex &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="kw">as.Date</span>(<span class="st">&quot;2020-10-10&quot;</span>), <span class="dt">by =</span><span class="st">&quot;day&quot;</span>, <span class="dt">length.out =</span> n)</span>
<span id="cb48-11"><a href="unit-root-tests.html#cb48-11"></a>rwSeries &lt;-<span class="st"> </span><span class="kw">xts</span>(randomWalk, <span class="dt">order.by =</span> timeIndex)</span>
<span id="cb48-12"><a href="unit-root-tests.html#cb48-12"></a><span class="kw">plot</span>(rwSeries, <span class="dt">main =</span> <span class="st">&quot;Data generated from a random walk process&quot;</span>)</span></code></pre></div>
<p><img src="timeseries2020_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="unit-root-tests.html#cb49-1"></a><span class="kw">summary</span>(<span class="kw">ur.df</span>(rwSeries, <span class="dt">selectlags =</span> <span class="st">&quot;Fixed&quot;</span>, <span class="dt">lags =</span> <span class="dv">0</span>, <span class="dt">type =</span> <span class="st">&quot;none&quot;</span>))</span></code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression none 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 - 1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.0633 -0.6613  0.0420  0.7365  3.3881 
## 
## Coefficients:
##          Estimate Std. Error t value Pr(&gt;|t|)
## z.lag.1 0.0007048  0.0016385    0.43    0.667
## 
## Residual standard error: 1.001 on 998 degrees of freedom
## Multiple R-squared:  0.0001854,  Adjusted R-squared:  -0.0008164 
## F-statistic: 0.1851 on 1 and 998 DF,  p-value: 0.6672
## 
## 
## Value of test-statistic is: 0.4302 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau1 -2.58 -1.95 -1.62</code></pre>
<p>In the case of the random-walk data we cannot reject the null hypothesis (has unit-root), because the value of the t-statistic is -0.691 and it is greater even than the critical value at 10 percent (-1.62).</p>
</div>
<div id="non-zero-level-no-trend" class="section level3">
<h3><span class="header-section-number">4.1.2</span> Non-zero level, no trend</h3>
<p>An important aspect of using the Dickey-Fuller test is that it is quite sensitive to deviations from its assumptions about the deterministic parts of the model (level and trend). Up to now our regression equation was:</p>
<p><span class="math display">\[
\Delta y_{t} = (\alpha_1 - 1)y_{t - 1} + u_{t}
\]</span>
and it is appropriate for data without a trend that fluctuate around zero.</p>
<p>Let us see what happens when we perform the Dickey-Fuller for data with non-zero level. Again, it is easier to use a simulation to illustrate the problem. We will use the same data from the AR(1) model with <span class="math inline">\(\alpha_1 = 0.7\)</span> from the previous example and add a constant to all the values.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="unit-root-tests.html#cb51-1"></a>stationaryAR1WithLevel &lt;-<span class="st"> </span>stationaryAR1 <span class="op">+</span><span class="st"> </span><span class="dv">100</span></span>
<span id="cb51-2"><a href="unit-root-tests.html#cb51-2"></a><span class="kw">plot</span>(stationaryAR1WithLevel, <span class="dt">main=</span><span class="st">&quot;AR(1) with alpha_1 = 0.7 and delta = 100&quot;</span>)</span></code></pre></div>
<p><img src="timeseries2020_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>We see that the only difference from the previous example is that the values of the AR(1) data fluctuate around 100 instead of 0.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="unit-root-tests.html#cb52-1"></a><span class="kw">summary</span>(<span class="kw">ur.df</span>(stationaryAR1WithLevel, <span class="dt">selectlags =</span> <span class="st">&quot;Fixed&quot;</span>, <span class="dt">lags =</span> <span class="dv">0</span>, <span class="dt">type =</span> <span class="st">&quot;none&quot;</span>))</span></code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression none 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 - 1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.2257 -0.6875  0.0074  0.7213  3.6709 
## 
## Coefficients:
##           Estimate Std. Error t value Pr(&gt;|t|)
## z.lag.1 -6.699e-05  3.457e-04  -0.194    0.846
## 
## Residual standard error: 1.094 on 998 degrees of freedom
## Multiple R-squared:  3.761e-05,  Adjusted R-squared:  -0.0009644 
## F-statistic: 0.03754 on 1 and 998 DF,  p-value: 0.8464
## 
## 
## Value of test-statistic is: -0.1937 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau1 -2.58 -1.95 -1.62</code></pre>
<p>Although there is no unit root in the data we see that the Dicke-Fuller test fails to reject the null hypothesis, because -0.1937 (t-statistic) &gt; -1.62 (critical value). This happens because we need to account for the non-zero level in the regression equation. Adding a constant it now becomes:</p>
<p><span class="math display">\[
\Delta y_{t} = \delta + (\alpha_1 - 1)y_{t - 1} + u_{t}
\]</span>
To use this equation when testing, set the <code>type = "drift"</code> option in <code>ur.df</code>.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="unit-root-tests.html#cb54-1"></a><span class="kw">summary</span>(<span class="kw">ur.df</span>(stationaryAR1WithLevel, <span class="dt">selectlags =</span> <span class="st">&quot;Fixed&quot;</span>, <span class="dt">lags =</span> <span class="dv">0</span>, <span class="dt">type =</span> <span class="st">&quot;drift&quot;</span>))</span></code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression drift 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 + 1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.8662 -0.6541 -0.0112  0.6532  3.1860 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 32.68748    2.34354   13.95   &lt;2e-16 ***
## z.lag.1     -0.32670    0.02342  -13.95   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.001 on 997 degrees of freedom
## Multiple R-squared:  0.1633, Adjusted R-squared:  0.1625 
## F-statistic: 194.6 on 1 and 997 DF,  p-value: &lt; 2.2e-16
## 
## 
## Value of test-statistic is: -13.9495 97.2945 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau2 -3.43 -2.86 -2.57
## phi1  6.43  4.59  3.78</code></pre>
<p>Now compare the value of the t-statistic (-13.95) to the first set of critical values (tau2 -3.43 -2.86 -2.57). This time the test rejects the null hypothesis of a unit root at any reasonable significance level, because the value of the t-statistic is less than the critical value at 1pct (-3.43).</p>
</div>
<div id="trend" class="section level3">
<h3><span class="header-section-number">4.1.3</span> Trend</h3>
<p>Apart from a non-zero level we often want to perform unit-root tests with data that has trend (systematic increase/decrease with time). Let us look again at the AR(1) data with <span class="math inline">\(\alpha_1 = 0.7\)</span> and add a linear trend to it. Afterwards we will perform the Dickey-Fuller test and see how it performs.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="unit-root-tests.html#cb56-1"></a>linearTrend &lt;-<span class="st"> </span><span class="fl">0.06</span><span class="op">*</span>(<span class="dv">1</span><span class="op">:</span>n)</span>
<span id="cb56-2"><a href="unit-root-tests.html#cb56-2"></a>trendStationary &lt;-<span class="st"> </span>linearTrend <span class="op">+</span><span class="st"> </span>stationaryAR1</span>
<span id="cb56-3"><a href="unit-root-tests.html#cb56-3"></a><span class="kw">plot</span>(trendStationary, <span class="dt">main=</span><span class="st">&quot;AR(1) with alpha_1 = 0.7 and a linear trend.&quot;</span>)</span></code></pre></div>
<p><img src="timeseries2020_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="unit-root-tests.html#cb57-1"></a><span class="kw">summary</span>(<span class="kw">ur.df</span>(trendStationary, <span class="dt">selectlags =</span> <span class="st">&quot;Fixed&quot;</span>, <span class="dt">lags =</span> <span class="dv">0</span>, <span class="dt">type =</span> <span class="st">&quot;drift&quot;</span>))</span></code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression drift 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 + 1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -3.2357 -0.7118 -0.0056  0.7250  3.6190 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept)  0.120038   0.069074   1.738   0.0826 .
## z.lag.1     -0.002022   0.001989  -1.017   0.3096  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.094 on 997 degrees of freedom
## Multiple R-squared:  0.001035,   Adjusted R-squared:  3.343e-05 
## F-statistic: 1.033 on 1 and 997 DF,  p-value: 0.3096
## 
## 
## Value of test-statistic is: -1.0165 1.9838 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau2 -3.43 -2.86 -2.57
## phi1  6.43  4.59  3.78</code></pre>
<p>From the output of <code>ur.df</code> we see that the Dickey-Fuller test with drift that we
used in the previous example fails to reject the null hypothesis of a unit root, because
the value of the t-statistic (-1.0165) is greater that the critical value at 10pct (-2.57). This is unexpected, because we know that there is no unit root in our generated data. This result happens here, because we havn’t accounted for the linear trend in our regression equation.</p>
<p>Let us add a term for the linear trend.</p>
<p><span class="math display">\[
\Delta y_{t} = \delta + \beta t + (\alpha_1 - 1)y_{t - 1} + u_{t}
\]</span>
To use the trend equation with <code>ur.df</code>, specify the <code>type="trend"</code> option.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="unit-root-tests.html#cb59-1"></a><span class="kw">summary</span>(<span class="kw">ur.df</span>(trendStationary, <span class="dt">selectlags =</span> <span class="st">&quot;Fixed&quot;</span>, <span class="dt">lags =</span> <span class="dv">0</span>, <span class="dt">type =</span> <span class="st">&quot;trend&quot;</span>))</span></code></pre></div>
<pre><code>## 
## ############################################### 
## # Augmented Dickey-Fuller Test Unit Root Test # 
## ############################################### 
## 
## Test regression trend 
## 
## 
## Call:
## lm(formula = z.diff ~ z.lag.1 + 1 + tt)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -2.8694 -0.6619 -0.0120  0.6560  3.1997 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  0.057687   0.063402    0.91    0.363    
## z.lag.1     -0.326933   0.023439  -13.95   &lt;2e-16 ***
## tt           0.019655   0.001414   13.90   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.001 on 996 degrees of freedom
## Multiple R-squared:  0.1634, Adjusted R-squared:  0.1617 
## F-statistic: 97.27 on 2 and 996 DF,  p-value: &lt; 2.2e-16
## 
## 
## Value of test-statistic is: -13.948 66.0156 97.2733 
## 
## Critical values for test statistics: 
##       1pct  5pct 10pct
## tau3 -3.96 -3.41 -3.12
## phi2  6.09  4.68  4.03
## phi3  8.27  6.25  5.34</code></pre>
<p>We see that adjusting the regression equation leads the Dickey-Fuller test to reject the null hypothesis of unit root, because the value of the t-statistic (-13.948) is less even than the critical value at 1pct (-3.96).</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="fit.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/01-intro.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["timeseries2020.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
